# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install black
      - run: black --check .

  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install isort
      - run: isort --check-only --profile=black .

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install flake8
      - run: flake8 --max-line-length=88 .

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install project & dev tools
        run: pip install -e .[dev]
      - name: Run Mypy
        run: mypy src/

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -e .[dev]
      - name: Run tests & collect coverage
        run: |
          pytest \
            --cov=safechess \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml \
            tests/
      - name: Show workspace layout & coverage file
        run: |
          echo "→ PWD: $(pwd)"
          echo "→ Listing top-level files:"
          ls -1
          echo "→ Recursive find (3 levels):"
          find . -maxdepth 3 | sed 's/^/  /'
          echo "→ coverage.xml head:"
          head -n 20 coverage.xml || true
          echo "→ coverage.xml lines:"
          wc -l coverage.xml || true

  codecov:
    name: Codecov
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: '**/coverage.xml'
          verbose: true
          fail_ci_if_error: true
